import type { NextPage } from 'next'
import Head from 'next/head'
import { Hero } from '@components/Hero/Hero'
import { Main } from '@src/components/Layout/Main'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MUI Starter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main>
        <Hero />
      </Main>
    </div>
  )
}

export default Home
